### ISSUE TITLE
Problem with npm install when using loopback-connector-db2 on Linux

### ISSUE THREAD

**Issue by ninoguba** [strongloop/loopback-connector-db2#93]
Getting this error when running npm install:

make: Entering directory '/home/primeadmin/prime/prime-app/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
odbc_bindings.target.mk:104: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
make: Leaving directory '/home/primeadmin/prime/prime-app/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=true
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: g++: Command not found
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/primeadmin/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.49-92.11-default
gyp ERR! command "/home/primeadmin/.nvm/versions/node/v7.6.0/bin/node" "/home/primeadmin/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/home/primeadmin/prime/prime-app/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /home/primeadmin/prime/prime-app/node_modules/ibm_db
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=true' }

npm ERR! Linux 4.4.49-92.11-default
npm ERR! argv "/home/primeadmin/.nvm/versions/node/v7.6.0/bin/node" "/home/primeadmin/.nvm/versions/node/v7.6.0/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ibm_db@2.0.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.0.0 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

**Comment by ninoguba** [comment]
Issue resolved.  I had to install gcc and gcc-c++ as they were missing.
